# src/pymock/constants/operators.py

TARGET_OPERATOR_MAP: dict[str, set[str]] = {
    "body": {
        "equals",
        "regex",
        "regex(i)",
        "null",
        "empty array",
        "array includes",
        "valid JSON schema",
    },
    "params": {
        "equals",
        "regex",
        "regex(i)",
        "null",
        "empty array",
        "array includes",
        "valid JSON schema",
    },
    "headers": {
        "equals",
        "regex",
        "regex(i)",
        "null",
        "empty array",
        "array includes",
        "valid JSON schema",
    },
    "route_params": {"equals", "regex", "regex(i)", "null", "valid JSON schema"},
    "path": {"equals", "regex", "regex(i)"},
    "method": {"equals", "regex", "regex(i)"},
    "number": {"equals", "regex", "regex(i)"},
    "global_variable": {
        "equals",
        "regex",
        "regex(i)",
        "null",
        "empty array",
        "array includes",
        "valid JSON schema",
    },
    "data_bucket": {
        "equals",
        "regex",
        "regex(i)",
        "null",
        "empty array",
        "array includes",
        "valid JSON schema",
    },
}
